// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/gobuffalo/lush/ast"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "DOC",
			pos:  position{line: 10, col: 1, offset: 88},
			expr: &actionExpr{
				pos: position{line: 10, col: 8, offset: 95},
				run: (*parser).callonDOC1,
				expr: &seqExpr{
					pos: position{line: 10, col: 8, offset: 95},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 10, col: 8, offset: 95},
							label: "stmts",
							expr: &oneOrMoreExpr{
								pos: position{line: 10, col: 14, offset: 101},
								expr: &seqExpr{
									pos: position{line: 10, col: 15, offset: 102},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 10, col: 15, offset: 102},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 10, col: 17, offset: 104},
											name: "STATEMENT",
										},
										&ruleRefExpr{
											pos:  position{line: 10, col: 27, offset: 114},
											name: "_",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 10, col: 31, offset: 118},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "STATEMENT",
			pos:  position{line: 15, col: 1, offset: 204},
			expr: &actionExpr{
				pos: position{line: 15, col: 14, offset: 217},
				run: (*parser).callonSTATEMENT1,
				expr: &seqExpr{
					pos: position{line: 15, col: 14, offset: 217},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 15, col: 14, offset: 217},
							label: "s",
							expr: &choiceExpr{
								pos: position{line: 15, col: 18, offset: 221},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 15, col: 18, offset: 221},
										name: "COMMENT",
									},
									&ruleRefExpr{
										pos:  position{line: 15, col: 28, offset: 231},
										name: "NULL",
									},
									&ruleRefExpr{
										pos:  position{line: 15, col: 35, offset: 238},
										name: "LET",
									},
									&ruleRefExpr{
										pos:  position{line: 15, col: 41, offset: 244},
										name: "VAR",
									},
									&ruleRefExpr{
										pos:  position{line: 15, col: 47, offset: 250},
										name: "ASSIGN",
									},
									&ruleRefExpr{
										pos:  position{line: 15, col: 56, offset: 259},
										name: "IF",
									},
									&ruleRefExpr{
										pos:  position{line: 15, col: 61, offset: 264},
										name: "IFOR",
									},
									&ruleRefExpr{
										pos:  position{line: 15, col: 68, offset: 271},
										name: "FOR",
									},
									&ruleRefExpr{
										pos:  position{line: 15, col: 74, offset: 277},
										name: "RANGE",
									},
									&ruleRefExpr{
										pos:  position{line: 15, col: 83, offset: 286},
										name: "FCALL",
									},
									&ruleRefExpr{
										pos:  position{line: 15, col: 91, offset: 294},
										name: "RETURN",
									},
									&ruleRefExpr{
										pos:  position{line: 15, col: 100, offset: 303},
										name: "CALL",
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 15, col: 107, offset: 310},
							expr: &litMatcher{
								pos:        position{line: 15, col: 107, offset: 310},
								val:        ";",
								ignoreCase: false,
							},
						},
					},
				},
			},
		},
		{
			name: "EXPRARG",
			pos:  position{line: 19, col: 1, offset: 336},
			expr: &choiceExpr{
				pos: position{line: 19, col: 13, offset: 348},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 19, col: 13, offset: 348},
						name: "POPEX",
					},
					&ruleRefExpr{
						pos:  position{line: 19, col: 21, offset: 356},
						name: "CALL",
					},
					&ruleRefExpr{
						pos:  position{line: 19, col: 28, offset: 363},
						name: "NUMBER",
					},
					&ruleRefExpr{
						pos:  position{line: 19, col: 37, offset: 372},
						name: "STRING",
					},
					&ruleRefExpr{
						pos:  position{line: 19, col: 46, offset: 381},
						name: "BOOL",
					},
					&ruleRefExpr{
						pos:  position{line: 19, col: 53, offset: 388},
						name: "ARRAY",
					},
					&ruleRefExpr{
						pos:  position{line: 19, col: 61, offset: 396},
						name: "MAP",
					},
					&ruleRefExpr{
						pos:  position{line: 19, col: 67, offset: 402},
						name: "NULL",
					},
					&ruleRefExpr{
						pos:  position{line: 19, col: 74, offset: 409},
						name: "IDENT",
					},
				},
			},
		},
		{
			name: "OP",
			pos:  position{line: 21, col: 1, offset: 417},
			expr: &actionExpr{
				pos: position{line: 21, col: 7, offset: 423},
				run: (*parser).callonOP1,
				expr: &choiceExpr{
					pos: position{line: 21, col: 9, offset: 425},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 21, col: 9, offset: 425},
							val:        "&&",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 21, col: 16, offset: 432},
							val:        "||",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 21, col: 23, offset: 439},
							val:        "<=",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 21, col: 30, offset: 446},
							val:        ">=",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 21, col: 37, offset: 453},
							val:        "==",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 21, col: 44, offset: 460},
							val:        "!=",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 21, col: 51, offset: 467},
							val:        "~=",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 21, col: 58, offset: 474},
							val:        "+",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 21, col: 64, offset: 480},
							val:        "-",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 21, col: 70, offset: 486},
							val:        "*",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 21, col: 76, offset: 492},
							val:        "/",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 21, col: 82, offset: 498},
							val:        "%",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 21, col: 88, offset: 504},
							val:        ">",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 21, col: 94, offset: 510},
							val:        "<",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "OPEX",
			pos:  position{line: 25, col: 1, offset: 549},
			expr: &actionExpr{
				pos: position{line: 25, col: 9, offset: 557},
				run: (*parser).callonOPEX1,
				expr: &seqExpr{
					pos: position{line: 25, col: 9, offset: 557},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 25, col: 9, offset: 557},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 25, col: 11, offset: 559},
							label: "a",
							expr: &ruleRefExpr{
								pos:  position{line: 25, col: 14, offset: 562},
								name: "EXPRARG",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 25, col: 23, offset: 571},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 25, col: 25, offset: 573},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 25, col: 28, offset: 576},
								name: "OP",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 25, col: 31, offset: 579},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 25, col: 33, offset: 581},
							label: "b",
							expr: &choiceExpr{
								pos: position{line: 25, col: 36, offset: 584},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 25, col: 36, offset: 584},
										name: "OPEX",
									},
									&ruleRefExpr{
										pos:  position{line: 25, col: 43, offset: 591},
										name: "EXPRARG",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 25, col: 52, offset: 600},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 25, col: 54, offset: 602},
							expr: &litMatcher{
								pos:        position{line: 25, col: 54, offset: 602},
								val:        ";",
								ignoreCase: false,
							},
						},
					},
				},
			},
		},
		{
			name: "POPEX",
			pos:  position{line: 29, col: 1, offset: 650},
			expr: &actionExpr{
				pos: position{line: 29, col: 10, offset: 659},
				run: (*parser).callonPOPEX1,
				expr: &seqExpr{
					pos: position{line: 29, col: 10, offset: 659},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 29, col: 10, offset: 659},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 12, offset: 661},
							name: "LP",
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 15, offset: 664},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 29, col: 17, offset: 666},
							label: "a",
							expr: &ruleRefExpr{
								pos:  position{line: 29, col: 20, offset: 669},
								name: "EXPRARG",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 29, offset: 678},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 29, col: 31, offset: 680},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 29, col: 34, offset: 683},
								name: "OP",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 37, offset: 686},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 29, col: 39, offset: 688},
							label: "b",
							expr: &ruleRefExpr{
								pos:  position{line: 29, col: 42, offset: 691},
								name: "EXPRARG",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 51, offset: 700},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 53, offset: 702},
							name: "RP",
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 56, offset: 705},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 29, col: 58, offset: 707},
							expr: &litMatcher{
								pos:        position{line: 29, col: 58, offset: 707},
								val:        ";",
								ignoreCase: false,
							},
						},
					},
				},
			},
		},
		{
			name: "IF",
			pos:  position{line: 33, col: 1, offset: 756},
			expr: &actionExpr{
				pos: position{line: 33, col: 7, offset: 762},
				run: (*parser).callonIF1,
				expr: &seqExpr{
					pos: position{line: 33, col: 7, offset: 762},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 33, col: 7, offset: 762},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 33, col: 9, offset: 764},
							val:        "if",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 33, col: 14, offset: 769},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 33, col: 16, offset: 771},
							label: "p",
							expr: &zeroOrOneExpr{
								pos: position{line: 33, col: 18, offset: 773},
								expr: &choiceExpr{
									pos: position{line: 33, col: 21, offset: 776},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 33, col: 21, offset: 776},
											name: "VAR",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 27, offset: 782},
											name: "LET",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 33, col: 35, offset: 790},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 33, col: 37, offset: 792},
							expr: &litMatcher{
								pos:        position{line: 33, col: 37, offset: 792},
								val:        ";",
								ignoreCase: false,
							},
						},
						&ruleRefExpr{
							pos:  position{line: 33, col: 42, offset: 797},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 33, col: 45, offset: 800},
							label: "s",
							expr: &choiceExpr{
								pos: position{line: 33, col: 48, offset: 803},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 33, col: 48, offset: 803},
										exprs: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 33, col: 48, offset: 803},
												name: "LP",
											},
											&ruleRefExpr{
												pos:  position{line: 33, col: 51, offset: 806},
												name: "_",
											},
											&choiceExpr{
												pos: position{line: 33, col: 54, offset: 809},
												alternatives: []interface{}{
													&ruleRefExpr{
														pos:  position{line: 33, col: 54, offset: 809},
														name: "BOOL",
													},
													&ruleRefExpr{
														pos:  position{line: 33, col: 61, offset: 816},
														name: "OPEX",
													},
													&ruleRefExpr{
														pos:  position{line: 33, col: 68, offset: 823},
														name: "POPEX",
													},
												},
											},
											&ruleRefExpr{
												pos:  position{line: 33, col: 76, offset: 831},
												name: "_",
											},
											&ruleRefExpr{
												pos:  position{line: 33, col: 78, offset: 833},
												name: "RP",
											},
										},
									},
									&choiceExpr{
										pos: position{line: 33, col: 84, offset: 839},
										alternatives: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 33, col: 84, offset: 839},
												name: "BOOL",
											},
											&ruleRefExpr{
												pos:  position{line: 33, col: 91, offset: 846},
												name: "OPEX",
											},
											&ruleRefExpr{
												pos:  position{line: 33, col: 98, offset: 853},
												name: "POPEX",
											},
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 33, col: 107, offset: 862},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 33, col: 109, offset: 864},
							label: "b",
							expr: &ruleRefExpr{
								pos:  position{line: 33, col: 111, offset: 866},
								name: "BLOCK",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 33, col: 117, offset: 872},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 33, col: 119, offset: 874},
							label: "e",
							expr: &zeroOrMoreExpr{
								pos: position{line: 33, col: 121, offset: 876},
								expr: &choiceExpr{
									pos: position{line: 33, col: 122, offset: 877},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 33, col: 122, offset: 877},
											name: "ELSEIF",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 131, offset: 886},
											name: "ELSE",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ELSE",
			pos:  position{line: 37, col: 1, offset: 928},
			expr: &actionExpr{
				pos: position{line: 37, col: 9, offset: 936},
				run: (*parser).callonELSE1,
				expr: &seqExpr{
					pos: position{line: 37, col: 9, offset: 936},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 37, col: 9, offset: 936},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 37, col: 11, offset: 938},
							val:        "else",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 37, col: 18, offset: 945},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 37, col: 20, offset: 947},
							label: "b",
							expr: &ruleRefExpr{
								pos:  position{line: 37, col: 22, offset: 949},
								name: "BLOCK",
							},
						},
					},
				},
			},
		},
		{
			name: "ELSEIF",
			pos:  position{line: 41, col: 1, offset: 983},
			expr: &actionExpr{
				pos: position{line: 41, col: 11, offset: 993},
				run: (*parser).callonELSEIF1,
				expr: &seqExpr{
					pos: position{line: 41, col: 11, offset: 993},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 41, col: 11, offset: 993},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 41, col: 13, offset: 995},
							val:        "else",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 41, col: 20, offset: 1002},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 41, col: 22, offset: 1004},
							label: "i",
							expr: &ruleRefExpr{
								pos:  position{line: 41, col: 24, offset: 1006},
								name: "IF",
							},
						},
					},
				},
			},
		},
		{
			name: "INTEGER",
			pos:  position{line: 45, col: 1, offset: 1039},
			expr: &actionExpr{
				pos: position{line: 45, col: 12, offset: 1050},
				run: (*parser).callonINTEGER1,
				expr: &seqExpr{
					pos: position{line: 45, col: 12, offset: 1050},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 45, col: 12, offset: 1050},
							expr: &litMatcher{
								pos:        position{line: 45, col: 12, offset: 1050},
								val:        "-",
								ignoreCase: false,
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 45, col: 17, offset: 1055},
							expr: &charClassMatcher{
								pos:        position{line: 45, col: 17, offset: 1055},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "FLOAT",
			pos:  position{line: 49, col: 1, offset: 1098},
			expr: &actionExpr{
				pos: position{line: 49, col: 10, offset: 1107},
				run: (*parser).callonFLOAT1,
				expr: &seqExpr{
					pos: position{line: 49, col: 10, offset: 1107},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 49, col: 10, offset: 1107},
							name: "INTEGER",
						},
						&zeroOrOneExpr{
							pos: position{line: 49, col: 18, offset: 1115},
							expr: &litMatcher{
								pos:        position{line: 49, col: 18, offset: 1115},
								val:        ".",
								ignoreCase: false,
							},
						},
						&ruleRefExpr{
							pos:  position{line: 49, col: 23, offset: 1120},
							name: "INTEGER",
						},
					},
				},
			},
		},
		{
			name: "UN",
			pos:  position{line: 53, col: 1, offset: 1162},
			expr: &litMatcher{
				pos:        position{line: 53, col: 7, offset: 1168},
				val:        "_",
				ignoreCase: false,
			},
		},
		{
			name: "IDENT",
			pos:  position{line: 55, col: 1, offset: 1173},
			expr: &actionExpr{
				pos: position{line: 55, col: 10, offset: 1182},
				run: (*parser).callonIDENT1,
				expr: &seqExpr{
					pos: position{line: 55, col: 10, offset: 1182},
					exprs: []interface{}{
						&oneOrMoreExpr{
							pos: position{line: 55, col: 10, offset: 1182},
							expr: &charClassMatcher{
								pos:        position{line: 55, col: 10, offset: 1182},
								val:        "[a-zA-Z]",
								ranges:     []rune{'a', 'z', 'A', 'Z'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 55, col: 20, offset: 1192},
							expr: &charClassMatcher{
								pos:        position{line: 55, col: 22, offset: 1194},
								val:        "[0-9a-zA-Z_]",
								chars:      []rune{'_'},
								ranges:     []rune{'0', '9', 'a', 'z', 'A', 'Z'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "NUMBER",
			pos:  position{line: 59, col: 1, offset: 1243},
			expr: &choiceExpr{
				pos: position{line: 59, col: 12, offset: 1254},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 59, col: 12, offset: 1254},
						name: "FLOAT",
					},
					&ruleRefExpr{
						pos:  position{line: 59, col: 20, offset: 1262},
						name: "INTEGER",
					},
				},
			},
		},
		{
			name: "LETV",
			pos:  position{line: 61, col: 1, offset: 1272},
			expr: &choiceExpr{
				pos: position{line: 61, col: 11, offset: 1282},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 61, col: 11, offset: 1282},
						name: "ACCESS",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 20, offset: 1291},
						name: "NULL",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 27, offset: 1298},
						name: "POPEX",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 35, offset: 1306},
						name: "OPEX",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 42, offset: 1313},
						name: "FCALL",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 50, offset: 1321},
						name: "FUNC",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 57, offset: 1328},
						name: "CALL",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 64, offset: 1335},
						name: "MAP",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 70, offset: 1341},
						name: "ARRAY",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 77, offset: 1348},
						name: "BOOL",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 84, offset: 1355},
						name: "STRING",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 93, offset: 1364},
						name: "NUMBER",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 102, offset: 1373},
						name: "NULL",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 109, offset: 1380},
						name: "IDENT",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 117, offset: 1388},
						name: "FOR",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 123, offset: 1394},
						name: "RANGE",
					},
				},
			},
		},
		{
			name: "LET",
			pos:  position{line: 63, col: 1, offset: 1404},
			expr: &actionExpr{
				pos: position{line: 63, col: 8, offset: 1411},
				run: (*parser).callonLET1,
				expr: &seqExpr{
					pos: position{line: 63, col: 8, offset: 1411},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 63, col: 8, offset: 1411},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 63, col: 10, offset: 1413},
							val:        "let",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 63, col: 16, offset: 1419},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 63, col: 18, offset: 1421},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 63, col: 23, offset: 1426},
								name: "IDENT",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 63, col: 29, offset: 1432},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 63, col: 31, offset: 1434},
							val:        "=",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 63, col: 35, offset: 1438},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 63, col: 37, offset: 1440},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 63, col: 43, offset: 1446},
								name: "LETV",
							},
						},
					},
				},
			},
		},
		{
			name: "VAR",
			pos:  position{line: 67, col: 1, offset: 1488},
			expr: &actionExpr{
				pos: position{line: 67, col: 8, offset: 1495},
				run: (*parser).callonVAR1,
				expr: &seqExpr{
					pos: position{line: 67, col: 8, offset: 1495},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 67, col: 8, offset: 1495},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 67, col: 10, offset: 1497},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 67, col: 15, offset: 1502},
								name: "IDENT",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 67, col: 21, offset: 1508},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 67, col: 23, offset: 1510},
							val:        ":=",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 67, col: 28, offset: 1515},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 67, col: 30, offset: 1517},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 67, col: 36, offset: 1523},
								name: "LETV",
							},
						},
					},
				},
			},
		},
		{
			name: "ASSIGN",
			pos:  position{line: 71, col: 1, offset: 1565},
			expr: &actionExpr{
				pos: position{line: 71, col: 11, offset: 1575},
				run: (*parser).callonASSIGN1,
				expr: &seqExpr{
					pos: position{line: 71, col: 11, offset: 1575},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 71, col: 11, offset: 1575},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 71, col: 13, offset: 1577},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 71, col: 18, offset: 1582},
								name: "IDENT",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 71, col: 24, offset: 1588},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 71, col: 26, offset: 1590},
							val:        "=",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 71, col: 30, offset: 1594},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 71, col: 32, offset: 1596},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 71, col: 38, offset: 1602},
								name: "LETV",
							},
						},
					},
				},
			},
		},
		{
			name: "ARG",
			pos:  position{line: 75, col: 1, offset: 1647},
			expr: &actionExpr{
				pos: position{line: 75, col: 8, offset: 1654},
				run: (*parser).callonARG1,
				expr: &seqExpr{
					pos: position{line: 75, col: 8, offset: 1654},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 75, col: 8, offset: 1654},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 75, col: 10, offset: 1656},
							label: "i",
							expr: &ruleRefExpr{
								pos:  position{line: 75, col: 12, offset: 1658},
								name: "LETV",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 75, col: 17, offset: 1663},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 75, col: 19, offset: 1665},
							expr: &litMatcher{
								pos:        position{line: 75, col: 19, offset: 1665},
								val:        ",",
								ignoreCase: false,
							},
						},
					},
				},
			},
		},
		{
			name: "BLOCK",
			pos:  position{line: 79, col: 1, offset: 1691},
			expr: &actionExpr{
				pos: position{line: 79, col: 10, offset: 1700},
				run: (*parser).callonBLOCK1,
				expr: &seqExpr{
					pos: position{line: 79, col: 10, offset: 1700},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 79, col: 10, offset: 1700},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 79, col: 12, offset: 1702},
							name: "LC",
						},
						&ruleRefExpr{
							pos:  position{line: 79, col: 15, offset: 1705},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 79, col: 17, offset: 1707},
							label: "s",
							expr: &zeroOrMoreExpr{
								pos: position{line: 79, col: 19, offset: 1709},
								expr: &choiceExpr{
									pos: position{line: 79, col: 21, offset: 1711},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 79, col: 21, offset: 1711},
											name: "CONTINUE",
										},
										&ruleRefExpr{
											pos:  position{line: 79, col: 32, offset: 1722},
											name: "BREAK",
										},
										&ruleRefExpr{
											pos:  position{line: 79, col: 40, offset: 1730},
											name: "STATEMENT",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 79, col: 53, offset: 1743},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 79, col: 55, offset: 1745},
							name: "RC",
						},
					},
				},
			},
		},
		{
			name: "FOR",
			pos:  position{line: 83, col: 1, offset: 1777},
			expr: &actionExpr{
				pos: position{line: 83, col: 8, offset: 1784},
				run: (*parser).callonFOR1,
				expr: &seqExpr{
					pos: position{line: 83, col: 8, offset: 1784},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 83, col: 8, offset: 1784},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 83, col: 10, offset: 1786},
							val:        "for ",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 83, col: 17, offset: 1793},
							label: "ax",
							expr: &seqExpr{
								pos: position{line: 83, col: 22, offset: 1798},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 83, col: 22, offset: 1798},
										name: "LP",
									},
									&oneOrMoreExpr{
										pos: position{line: 83, col: 25, offset: 1801},
										expr: &ruleRefExpr{
											pos:  position{line: 83, col: 25, offset: 1801},
											name: "ARG",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 83, col: 30, offset: 1806},
										name: "RP",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 83, col: 35, offset: 1811},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 83, col: 37, offset: 1813},
							val:        "in",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 83, col: 42, offset: 1818},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 83, col: 44, offset: 1820},
							label: "i",
							expr: &choiceExpr{
								pos: position{line: 83, col: 47, offset: 1823},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 83, col: 47, offset: 1823},
										name: "IDENT",
									},
									&ruleRefExpr{
										pos:  position{line: 83, col: 55, offset: 1831},
										name: "ARRAY",
									},
									&ruleRefExpr{
										pos:  position{line: 83, col: 63, offset: 1839},
										name: "MAP",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 83, col: 69, offset: 1845},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 83, col: 71, offset: 1847},
							label: "s",
							expr: &ruleRefExpr{
								pos:  position{line: 83, col: 73, offset: 1849},
								name: "BLOCK",
							},
						},
					},
				},
			},
		},
		{
			name: "RANGE",
			pos:  position{line: 87, col: 1, offset: 1889},
			expr: &actionExpr{
				pos: position{line: 87, col: 10, offset: 1898},
				run: (*parser).callonRANGE1,
				expr: &seqExpr{
					pos: position{line: 87, col: 10, offset: 1898},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 87, col: 10, offset: 1898},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 87, col: 12, offset: 1900},
							val:        "for ",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 87, col: 19, offset: 1907},
							label: "ax",
							expr: &oneOrMoreExpr{
								pos: position{line: 87, col: 24, offset: 1912},
								expr: &ruleRefExpr{
									pos:  position{line: 87, col: 24, offset: 1912},
									name: "ARG",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 87, col: 30, offset: 1918},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 87, col: 32, offset: 1920},
							val:        ":=",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 87, col: 37, offset: 1925},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 87, col: 39, offset: 1927},
							val:        "range",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 87, col: 47, offset: 1935},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 87, col: 49, offset: 1937},
							label: "i",
							expr: &choiceExpr{
								pos: position{line: 87, col: 52, offset: 1940},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 87, col: 52, offset: 1940},
										name: "IDENT",
									},
									&ruleRefExpr{
										pos:  position{line: 87, col: 60, offset: 1948},
										name: "ARRAY",
									},
									&ruleRefExpr{
										pos:  position{line: 87, col: 68, offset: 1956},
										name: "MAP",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 87, col: 74, offset: 1962},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 87, col: 76, offset: 1964},
							label: "s",
							expr: &ruleRefExpr{
								pos:  position{line: 87, col: 78, offset: 1966},
								name: "BLOCK",
							},
						},
					},
				},
			},
		},
		{
			name: "IFOR",
			pos:  position{line: 91, col: 1, offset: 2008},
			expr: &actionExpr{
				pos: position{line: 91, col: 9, offset: 2016},
				run: (*parser).callonIFOR1,
				expr: &seqExpr{
					pos: position{line: 91, col: 9, offset: 2016},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 91, col: 9, offset: 2016},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 91, col: 11, offset: 2018},
							val:        "for",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 91, col: 17, offset: 2024},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 91, col: 19, offset: 2026},
							label: "s",
							expr: &ruleRefExpr{
								pos:  position{line: 91, col: 21, offset: 2028},
								name: "BLOCK",
							},
						},
					},
				},
			},
		},
		{
			name: "ARRAY",
			pos:  position{line: 95, col: 1, offset: 2071},
			expr: &actionExpr{
				pos: position{line: 95, col: 10, offset: 2080},
				run: (*parser).callonARRAY1,
				expr: &seqExpr{
					pos: position{line: 95, col: 10, offset: 2080},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 95, col: 10, offset: 2080},
							name: "LB",
						},
						&ruleRefExpr{
							pos:  position{line: 95, col: 13, offset: 2083},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 95, col: 15, offset: 2085},
							label: "ax",
							expr: &zeroOrMoreExpr{
								pos: position{line: 95, col: 18, offset: 2088},
								expr: &ruleRefExpr{
									pos:  position{line: 95, col: 18, offset: 2088},
									name: "ARG",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 95, col: 23, offset: 2093},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 95, col: 25, offset: 2095},
							name: "RB",
						},
					},
				},
			},
		},
		{
			name: "ACCESS",
			pos:  position{line: 99, col: 1, offset: 2128},
			expr: &actionExpr{
				pos: position{line: 99, col: 11, offset: 2138},
				run: (*parser).callonACCESS1,
				expr: &seqExpr{
					pos: position{line: 99, col: 11, offset: 2138},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 99, col: 11, offset: 2138},
							label: "i",
							expr: &ruleRefExpr{
								pos:  position{line: 99, col: 14, offset: 2141},
								name: "IDENT",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 99, col: 21, offset: 2148},
							name: "LB",
						},
						&labeledExpr{
							pos:   position{line: 99, col: 24, offset: 2151},
							label: "key",
							expr: &choiceExpr{
								pos: position{line: 99, col: 29, offset: 2156},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 99, col: 29, offset: 2156},
										name: "NUMBER",
									},
									&ruleRefExpr{
										pos:  position{line: 99, col: 36, offset: 2163},
										name: "IDENT",
									},
									&ruleRefExpr{
										pos:  position{line: 99, col: 42, offset: 2169},
										name: "STRING",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 99, col: 50, offset: 2177},
							name: "RB",
						},
					},
				},
			},
		},
		{
			name: "RETURN",
			pos:  position{line: 103, col: 1, offset: 2215},
			expr: &actionExpr{
				pos: position{line: 103, col: 11, offset: 2225},
				run: (*parser).callonRETURN1,
				expr: &seqExpr{
					pos: position{line: 103, col: 11, offset: 2225},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 103, col: 11, offset: 2225},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 103, col: 13, offset: 2227},
							val:        "return",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 103, col: 22, offset: 2236},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 103, col: 24, offset: 2238},
							label: "s",
							expr: &zeroOrMoreExpr{
								pos: position{line: 103, col: 26, offset: 2240},
								expr: &ruleRefExpr{
									pos:  position{line: 103, col: 26, offset: 2240},
									name: "ARG",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "FARG",
			pos:  position{line: 107, col: 1, offset: 2275},
			expr: &actionExpr{
				pos: position{line: 107, col: 9, offset: 2283},
				run: (*parser).callonFARG1,
				expr: &seqExpr{
					pos: position{line: 107, col: 9, offset: 2283},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 107, col: 9, offset: 2283},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 107, col: 11, offset: 2285},
							label: "i",
							expr: &ruleRefExpr{
								pos:  position{line: 107, col: 14, offset: 2288},
								name: "IDENT",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 107, col: 21, offset: 2295},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 107, col: 23, offset: 2297},
							expr: &litMatcher{
								pos:        position{line: 107, col: 23, offset: 2297},
								val:        ",",
								ignoreCase: false,
							},
						},
					},
				},
			},
		},
		{
			name: "FUNC",
			pos:  position{line: 111, col: 1, offset: 2323},
			expr: &actionExpr{
				pos: position{line: 111, col: 9, offset: 2331},
				run: (*parser).callonFUNC1,
				expr: &seqExpr{
					pos: position{line: 111, col: 9, offset: 2331},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 111, col: 9, offset: 2331},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 111, col: 11, offset: 2333},
							val:        "func",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 111, col: 18, offset: 2340},
							name: "LP",
						},
						&labeledExpr{
							pos:   position{line: 111, col: 21, offset: 2343},
							label: "ax",
							expr: &zeroOrMoreExpr{
								pos: position{line: 111, col: 24, offset: 2346},
								expr: &ruleRefExpr{
									pos:  position{line: 111, col: 24, offset: 2346},
									name: "FARG",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 111, col: 30, offset: 2352},
							name: "RP",
						},
						&ruleRefExpr{
							pos:  position{line: 111, col: 33, offset: 2355},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 111, col: 35, offset: 2357},
							label: "s",
							expr: &ruleRefExpr{
								pos:  position{line: 111, col: 37, offset: 2359},
								name: "BLOCK",
							},
						},
					},
				},
			},
		},
		{
			name: "FCALL",
			pos:  position{line: 115, col: 1, offset: 2397},
			expr: &actionExpr{
				pos: position{line: 115, col: 10, offset: 2406},
				run: (*parser).callonFCALL1,
				expr: &seqExpr{
					pos: position{line: 115, col: 10, offset: 2406},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 115, col: 10, offset: 2406},
							label: "f",
							expr: &ruleRefExpr{
								pos:  position{line: 115, col: 12, offset: 2408},
								name: "FUNC",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 115, col: 17, offset: 2413},
							name: "LP",
						},
						&labeledExpr{
							pos:   position{line: 115, col: 20, offset: 2416},
							label: "ax",
							expr: &zeroOrMoreExpr{
								pos: position{line: 115, col: 23, offset: 2419},
								expr: &ruleRefExpr{
									pos:  position{line: 115, col: 23, offset: 2419},
									name: "ARG",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 115, col: 28, offset: 2424},
							name: "RP",
						},
						&ruleRefExpr{
							pos:  position{line: 115, col: 31, offset: 2427},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 115, col: 33, offset: 2429},
							label: "b",
							expr: &zeroOrOneExpr{
								pos: position{line: 115, col: 35, offset: 2431},
								expr: &ruleRefExpr{
									pos:  position{line: 115, col: 36, offset: 2432},
									name: "BLOCK",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CALL",
			pos:  position{line: 119, col: 1, offset: 2480},
			expr: &actionExpr{
				pos: position{line: 119, col: 9, offset: 2488},
				run: (*parser).callonCALL1,
				expr: &seqExpr{
					pos: position{line: 119, col: 9, offset: 2488},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 119, col: 9, offset: 2488},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 119, col: 11, offset: 2490},
							label: "i",
							expr: &ruleRefExpr{
								pos:  position{line: 119, col: 15, offset: 2494},
								name: "IDENT",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 119, col: 24, offset: 2503},
							expr: &litMatcher{
								pos:        position{line: 119, col: 24, offset: 2503},
								val:        ".",
								ignoreCase: false,
							},
						},
						&labeledExpr{
							pos:   position{line: 119, col: 30, offset: 2509},
							label: "y",
							expr: &zeroOrOneExpr{
								pos: position{line: 119, col: 32, offset: 2511},
								expr: &ruleRefExpr{
									pos:  position{line: 119, col: 33, offset: 2512},
									name: "IDENT",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 119, col: 41, offset: 2520},
							name: "LP",
						},
						&labeledExpr{
							pos:   position{line: 119, col: 44, offset: 2523},
							label: "ax",
							expr: &zeroOrMoreExpr{
								pos: position{line: 119, col: 47, offset: 2526},
								expr: &ruleRefExpr{
									pos:  position{line: 119, col: 47, offset: 2526},
									name: "ARG",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 119, col: 52, offset: 2531},
							name: "RP",
						},
						&ruleRefExpr{
							pos:  position{line: 119, col: 55, offset: 2534},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 119, col: 57, offset: 2536},
							label: "b",
							expr: &zeroOrOneExpr{
								pos: position{line: 119, col: 59, offset: 2538},
								expr: &ruleRefExpr{
									pos:  position{line: 119, col: 60, offset: 2539},
									name: "BLOCK",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "BOOL",
			pos:  position{line: 123, col: 1, offset: 2585},
			expr: &actionExpr{
				pos: position{line: 123, col: 9, offset: 2593},
				run: (*parser).callonBOOL1,
				expr: &choiceExpr{
					pos: position{line: 123, col: 10, offset: 2594},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 123, col: 10, offset: 2594},
							val:        "false",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 123, col: 20, offset: 2604},
							val:        "true",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "STRING",
			pos:  position{line: 127, col: 1, offset: 2645},
			expr: &actionExpr{
				pos: position{line: 127, col: 11, offset: 2655},
				run: (*parser).callonSTRING1,
				expr: &labeledExpr{
					pos:   position{line: 127, col: 11, offset: 2655},
					label: "s",
					expr: &choiceExpr{
						pos: position{line: 127, col: 14, offset: 2658},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 127, col: 14, offset: 2658},
								name: "MLSTRING",
							},
							&ruleRefExpr{
								pos:  position{line: 127, col: 25, offset: 2669},
								name: "DQSTRING",
							},
						},
					},
				},
			},
		},
		{
			name: "MLSTRING",
			pos:  position{line: 131, col: 1, offset: 2701},
			expr: &actionExpr{
				pos: position{line: 131, col: 13, offset: 2713},
				run: (*parser).callonMLSTRING1,
				expr: &seqExpr{
					pos: position{line: 131, col: 13, offset: 2713},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 131, col: 13, offset: 2713},
							val:        "`",
							ignoreCase: false,
						},
						&oneOrMoreExpr{
							pos: position{line: 131, col: 17, offset: 2717},
							expr: &charClassMatcher{
								pos:        position{line: 131, col: 17, offset: 2717},
								val:        "[^`]",
								chars:      []rune{'`'},
								ignoreCase: false,
								inverted:   true,
							},
						},
						&litMatcher{
							pos:        position{line: 131, col: 23, offset: 2723},
							val:        "`",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "DQSTRING",
			pos:  position{line: 135, col: 1, offset: 2763},
			expr: &actionExpr{
				pos: position{line: 135, col: 13, offset: 2775},
				run: (*parser).callonDQSTRING1,
				expr: &seqExpr{
					pos: position{line: 135, col: 13, offset: 2775},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 135, col: 13, offset: 2775},
							val:        "\"",
							ignoreCase: false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 135, col: 17, offset: 2779},
							expr: &choiceExpr{
								pos: position{line: 135, col: 19, offset: 2781},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 135, col: 19, offset: 2781},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 135, col: 19, offset: 2781},
												expr: &ruleRefExpr{
													pos:  position{line: 135, col: 20, offset: 2782},
													name: "DQEscapeChar",
												},
											},
											&anyMatcher{
												line: 135, col: 33, offset: 2795,
											},
										},
									},
									&seqExpr{
										pos: position{line: 135, col: 37, offset: 2799},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 135, col: 37, offset: 2799},
												val:        "\\",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 135, col: 42, offset: 2804},
												name: "DQEscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 135, col: 62, offset: 2824},
							val:        "\"",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "BREAK",
			pos:  position{line: 139, col: 1, offset: 2864},
			expr: &actionExpr{
				pos: position{line: 139, col: 10, offset: 2873},
				run: (*parser).callonBREAK1,
				expr: &seqExpr{
					pos: position{line: 139, col: 10, offset: 2873},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 139, col: 10, offset: 2873},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 139, col: 12, offset: 2875},
							val:        "break",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 139, col: 20, offset: 2883},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "CONTINUE",
			pos:  position{line: 143, col: 1, offset: 2916},
			expr: &actionExpr{
				pos: position{line: 143, col: 13, offset: 2928},
				run: (*parser).callonCONTINUE1,
				expr: &seqExpr{
					pos: position{line: 143, col: 13, offset: 2928},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 143, col: 13, offset: 2928},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 143, col: 15, offset: 2930},
							val:        "continue",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 143, col: 26, offset: 2941},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "NULL",
			pos:  position{line: 147, col: 1, offset: 2977},
			expr: &actionExpr{
				pos: position{line: 147, col: 8, offset: 2986},
				run: (*parser).callonNULL1,
				expr: &litMatcher{
					pos:        position{line: 147, col: 10, offset: 2988},
					val:        "nil",
					ignoreCase: false,
				},
			},
		},
		{
			name: "MAP",
			pos:  position{line: 151, col: 1, offset: 3025},
			expr: &actionExpr{
				pos: position{line: 151, col: 8, offset: 3032},
				run: (*parser).callonMAP1,
				expr: &seqExpr{
					pos: position{line: 151, col: 8, offset: 3032},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 151, col: 8, offset: 3032},
							name: "LC",
						},
						&ruleRefExpr{
							pos:  position{line: 151, col: 11, offset: 3035},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 151, col: 13, offset: 3037},
							label: "vals",
							expr: &zeroOrMoreExpr{
								pos: position{line: 151, col: 18, offset: 3042},
								expr: &seqExpr{
									pos: position{line: 151, col: 20, offset: 3044},
									exprs: []interface{}{
										&choiceExpr{
											pos: position{line: 151, col: 21, offset: 3045},
											alternatives: []interface{}{
												&ruleRefExpr{
													pos:  position{line: 151, col: 21, offset: 3045},
													name: "IDENT",
												},
												&ruleRefExpr{
													pos:  position{line: 151, col: 27, offset: 3051},
													name: "STRING",
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 151, col: 35, offset: 3059},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 151, col: 37, offset: 3061},
											val:        ":",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 151, col: 41, offset: 3065},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 151, col: 44, offset: 3068},
											name: "ARG",
										},
										&ruleRefExpr{
											pos:  position{line: 151, col: 49, offset: 3073},
											name: "_",
										},
										&zeroOrMoreExpr{
											pos: position{line: 151, col: 51, offset: 3075},
											expr: &litMatcher{
												pos:        position{line: 151, col: 52, offset: 3076},
												val:        ",",
												ignoreCase: false,
											},
										},
										&ruleRefExpr{
											pos:  position{line: 151, col: 58, offset: 3082},
											name: "_",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 151, col: 64, offset: 3088},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 151, col: 66, offset: 3090},
							name: "RC",
						},
					},
				},
			},
		},
		{
			name: "COMMENT",
			pos:  position{line: 155, col: 1, offset: 3123},
			expr: &actionExpr{
				pos: position{line: 155, col: 12, offset: 3134},
				run: (*parser).callonCOMMENT1,
				expr: &seqExpr{
					pos: position{line: 155, col: 12, offset: 3134},
					exprs: []interface{}{
						&choiceExpr{
							pos: position{line: 155, col: 13, offset: 3135},
							alternatives: []interface{}{
								&litMatcher{
									pos:        position{line: 155, col: 13, offset: 3135},
									val:        "#",
									ignoreCase: false,
								},
								&litMatcher{
									pos:        position{line: 155, col: 19, offset: 3141},
									val:        "//",
									ignoreCase: false,
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 155, col: 26, offset: 3148},
							label: "a",
							expr: &zeroOrMoreExpr{
								pos: position{line: 155, col: 28, offset: 3150},
								expr: &charClassMatcher{
									pos:        position{line: 155, col: 28, offset: 3150},
									val:        "[^\\n\\r]",
									chars:      []rune{'\n', '\r'},
									ignoreCase: false,
									inverted:   true,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "LP",
			pos:  position{line: 159, col: 1, offset: 3195},
			expr: &actionExpr{
				pos: position{line: 159, col: 7, offset: 3201},
				run: (*parser).callonLP1,
				expr: &litMatcher{
					pos:        position{line: 159, col: 7, offset: 3201},
					val:        "(",
					ignoreCase: false,
				},
			},
		},
		{
			name: "RP",
			pos:  position{line: 160, col: 1, offset: 3235},
			expr: &actionExpr{
				pos: position{line: 160, col: 7, offset: 3241},
				run: (*parser).callonRP1,
				expr: &litMatcher{
					pos:        position{line: 160, col: 7, offset: 3241},
					val:        ")",
					ignoreCase: false,
				},
			},
		},
		{
			name: "LB",
			pos:  position{line: 161, col: 1, offset: 3275},
			expr: &actionExpr{
				pos: position{line: 161, col: 7, offset: 3281},
				run: (*parser).callonLB1,
				expr: &litMatcher{
					pos:        position{line: 161, col: 7, offset: 3281},
					val:        "[",
					ignoreCase: false,
				},
			},
		},
		{
			name: "RB",
			pos:  position{line: 162, col: 1, offset: 3315},
			expr: &actionExpr{
				pos: position{line: 162, col: 7, offset: 3321},
				run: (*parser).callonRB1,
				expr: &litMatcher{
					pos:        position{line: 162, col: 7, offset: 3321},
					val:        "]",
					ignoreCase: false,
				},
			},
		},
		{
			name: "LC",
			pos:  position{line: 163, col: 1, offset: 3355},
			expr: &actionExpr{
				pos: position{line: 163, col: 7, offset: 3361},
				run: (*parser).callonLC1,
				expr: &litMatcher{
					pos:        position{line: 163, col: 7, offset: 3361},
					val:        "{",
					ignoreCase: false,
				},
			},
		},
		{
			name: "RC",
			pos:  position{line: 164, col: 1, offset: 3395},
			expr: &actionExpr{
				pos: position{line: 164, col: 7, offset: 3401},
				run: (*parser).callonRC1,
				expr: &litMatcher{
					pos:        position{line: 164, col: 7, offset: 3401},
					val:        "}",
					ignoreCase: false,
				},
			},
		},
		{
			name: "MLEscapeChar",
			pos:  position{line: 166, col: 1, offset: 3436},
			expr: &charClassMatcher{
				pos:        position{line: 166, col: 17, offset: 3452},
				val:        "[\\x00-\\x1f\\\\`]",
				chars:      []rune{'\\', '`'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "MLEscapeSequence",
			pos:  position{line: 167, col: 1, offset: 3467},
			expr: &choiceExpr{
				pos: position{line: 167, col: 21, offset: 3487},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 167, col: 21, offset: 3487},
						name: "MLSingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 167, col: 42, offset: 3508},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "MLSingleCharEscape",
			pos:  position{line: 168, col: 1, offset: 3522},
			expr: &charClassMatcher{
				pos:        position{line: 168, col: 23, offset: 3544},
				val:        "['\\\\/bfnrt]",
				chars:      []rune{'\'', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "DQEscapeChar",
			pos:  position{line: 170, col: 1, offset: 3557},
			expr: &charClassMatcher{
				pos:        position{line: 170, col: 17, offset: 3573},
				val:        "[\\x00-\\x1f\\\\\"]",
				chars:      []rune{'\\', '"'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "DQEscapeSequence",
			pos:  position{line: 171, col: 1, offset: 3588},
			expr: &choiceExpr{
				pos: position{line: 171, col: 21, offset: 3608},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 171, col: 21, offset: 3608},
						name: "DQSingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 171, col: 42, offset: 3629},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "DQSingleCharEscape",
			pos:  position{line: 172, col: 1, offset: 3643},
			expr: &charClassMatcher{
				pos:        position{line: 172, col: 23, offset: 3665},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 174, col: 1, offset: 3678},
			expr: &seqExpr{
				pos: position{line: 174, col: 17, offset: 3696},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 174, col: 17, offset: 3696},
						val:        "u",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 174, col: 21, offset: 3700},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 174, col: 30, offset: 3709},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 174, col: 39, offset: 3718},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 174, col: 48, offset: 3727},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 176, col: 1, offset: 3737},
			expr: &charClassMatcher{
				pos:        position{line: 176, col: 16, offset: 3754},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 178, col: 1, offset: 3761},
			expr: &charClassMatcher{
				pos:        position{line: 178, col: 23, offset: 3785},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 180, col: 1, offset: 3792},
			expr: &charClassMatcher{
				pos:        position{line: 180, col: 12, offset: 3805},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 182, col: 1, offset: 3816},
			expr: &actionExpr{
				pos: position{line: 182, col: 18, offset: 3835},
				run: (*parser).callon_1,
				expr: &zeroOrMoreExpr{
					pos: position{line: 182, col: 18, offset: 3835},
					expr: &charClassMatcher{
						pos:        position{line: 182, col: 18, offset: 3835},
						val:        "[ \\t\\r\\n]",
						chars:      []rune{' ', '\t', '\r', '\n'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 186, col: 1, offset: 3880},
			expr: &actionExpr{
				pos: position{line: 186, col: 8, offset: 3887},
				run: (*parser).callonEOF1,
				expr: &notExpr{
					pos: position{line: 186, col: 8, offset: 3887},
					expr: &anyMatcher{
						line: 186, col: 9, offset: 3888,
					},
				},
			},
		},
	},
}

func (c *current) onDOC1(stmts interface{}) (interface{}, error) {
	s, err := ast.NewStatements(stmts)
	return ast.Script{Statements: s}, err
}

func (p *parser) callonDOC1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDOC1(stack["stmts"])
}

func (c *current) onSTATEMENT1(s interface{}) (interface{}, error) {
	return s, nil
}

func (p *parser) callonSTATEMENT1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSTATEMENT1(stack["s"])
}

func (c *current) onOP1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonOP1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOP1()
}

func (c *current) onOPEX1(a, op, b interface{}) (interface{}, error) {
	return newOpExpression(c, a, op, b)
}

func (p *parser) callonOPEX1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOPEX1(stack["a"], stack["op"], stack["b"])
}

func (c *current) onPOPEX1(a, op, b interface{}) (interface{}, error) {
	return newPopExpression(c, a, op, b)
}

func (p *parser) callonPOPEX1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPOPEX1(stack["a"], stack["op"], stack["b"])
}

func (c *current) onIF1(p, s, b, e interface{}) (interface{}, error) {
	return newIf(c, p, s, b, e)
}

func (p *parser) callonIF1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIF1(stack["p"], stack["s"], stack["b"], stack["e"])
}

func (c *current) onELSE1(b interface{}) (interface{}, error) {
	return newElse(c, b)
}

func (p *parser) callonELSE1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onELSE1(stack["b"])
}

func (c *current) onELSEIF1(i interface{}) (interface{}, error) {
	return newElseIf(c, i)
}

func (p *parser) callonELSEIF1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onELSEIF1(stack["i"])
}

func (c *current) onINTEGER1() (interface{}, error) {
	return newInteger(c, c.text)
}

func (p *parser) callonINTEGER1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onINTEGER1()
}

func (c *current) onFLOAT1() (interface{}, error) {
	return newFloat(c, c.text)
}

func (p *parser) callonFLOAT1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFLOAT1()
}

func (c *current) onIDENT1() (interface{}, error) {
	return newIdent(c, c.text)
}

func (p *parser) callonIDENT1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIDENT1()
}

func (c *current) onLET1(name, value interface{}) (interface{}, error) {
	return newLet(c, name, value)
}

func (p *parser) callonLET1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLET1(stack["name"], stack["value"])
}

func (c *current) onVAR1(name, value interface{}) (interface{}, error) {
	return newVar(c, name, value)
}

func (p *parser) callonVAR1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVAR1(stack["name"], stack["value"])
}

func (c *current) onASSIGN1(name, value interface{}) (interface{}, error) {
	return newAssign(c, name, value)
}

func (p *parser) callonASSIGN1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onASSIGN1(stack["name"], stack["value"])
}

func (c *current) onARG1(i interface{}) (interface{}, error) {
	return i, nil
}

func (p *parser) callonARG1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onARG1(stack["i"])
}

func (c *current) onBLOCK1(s interface{}) (interface{}, error) {
	return newBlock(c, s)
}

func (p *parser) callonBLOCK1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBLOCK1(stack["s"])
}

func (c *current) onFOR1(ax, i, s interface{}) (interface{}, error) {
	return newFor(c, i, ax, s)
}

func (p *parser) callonFOR1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFOR1(stack["ax"], stack["i"], stack["s"])
}

func (c *current) onRANGE1(ax, i, s interface{}) (interface{}, error) {
	return newRange(c, i, ax, s)
}

func (p *parser) callonRANGE1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRANGE1(stack["ax"], stack["i"], stack["s"])
}

func (c *current) onIFOR1(s interface{}) (interface{}, error) {
	return newFor(c, nil, nil, s)
}

func (p *parser) callonIFOR1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIFOR1(stack["s"])
}

func (c *current) onARRAY1(ax interface{}) (interface{}, error) {
	return newArray(c, ax)
}

func (p *parser) callonARRAY1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onARRAY1(stack["ax"])
}

func (c *current) onACCESS1(i, key interface{}) (interface{}, error) {
	return newAccess(c, i, key)
}

func (p *parser) callonACCESS1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onACCESS1(stack["i"], stack["key"])
}

func (c *current) onRETURN1(s interface{}) (interface{}, error) {
	return newReturn(c, s)
}

func (p *parser) callonRETURN1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRETURN1(stack["s"])
}

func (c *current) onFARG1(i interface{}) (interface{}, error) {
	return i, nil
}

func (p *parser) callonFARG1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFARG1(stack["i"])
}

func (c *current) onFUNC1(ax, s interface{}) (interface{}, error) {
	return newFunc(c, ax, s)
}

func (p *parser) callonFUNC1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFUNC1(stack["ax"], stack["s"])
}

func (c *current) onFCALL1(f, ax, b interface{}) (interface{}, error) {
	return newCall(c, f, nil, ax, b)
}

func (p *parser) callonFCALL1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFCALL1(stack["f"], stack["ax"], stack["b"])
}

func (c *current) onCALL1(i, y, ax, b interface{}) (interface{}, error) {
	return newCall(c, i, y, ax, b)
}

func (p *parser) callonCALL1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCALL1(stack["i"], stack["y"], stack["ax"], stack["b"])
}

func (c *current) onBOOL1() (interface{}, error) {
	return newBool(c, c.text)
}

func (p *parser) callonBOOL1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBOOL1()
}

func (c *current) onSTRING1(s interface{}) (interface{}, error) {
	return s, nil
}

func (p *parser) callonSTRING1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSTRING1(stack["s"])
}

func (c *current) onMLSTRING1() (interface{}, error) {
	return ast.NewString(c.text)
}

func (p *parser) callonMLSTRING1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMLSTRING1()
}

func (c *current) onDQSTRING1() (interface{}, error) {
	return ast.NewString(c.text)
}

func (p *parser) callonDQSTRING1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDQSTRING1()
}

func (c *current) onBREAK1() (interface{}, error) {
	return ast.Break{}, nil
}

func (p *parser) callonBREAK1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBREAK1()
}

func (c *current) onCONTINUE1() (interface{}, error) {
	return ast.Continue{}, nil
}

func (p *parser) callonCONTINUE1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCONTINUE1()
}

func (c *current) onNULL1() (interface{}, error) {
	return ast.Nil{}, nil
}

func (p *parser) callonNULL1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNULL1()
}

func (c *current) onMAP1(vals interface{}) (interface{}, error) {
	return newMap(c, vals)
}

func (p *parser) callonMAP1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMAP1(stack["vals"])
}

func (c *current) onCOMMENT1(a interface{}) (interface{}, error) {
	return newComment(c, c.text)
}

func (p *parser) callonCOMMENT1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOMMENT1(stack["a"])
}

func (c *current) onLP1() (interface{}, error) {
	return ast.NewNoop(c.text)
}

func (p *parser) callonLP1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLP1()
}

func (c *current) onRP1() (interface{}, error) {
	return ast.NewNoop(c.text)
}

func (p *parser) callonRP1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRP1()
}

func (c *current) onLB1() (interface{}, error) {
	return ast.NewNoop(c.text)
}

func (p *parser) callonLB1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLB1()
}

func (c *current) onRB1() (interface{}, error) {
	return ast.NewNoop(c.text)
}

func (p *parser) callonRB1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRB1()
}

func (c *current) onLC1() (interface{}, error) {
	return ast.NewNoop(c.text)
}

func (p *parser) callonLC1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLC1()
}

func (c *current) onRC1() (interface{}, error) {
	return ast.NewNoop(c.text)
}

func (p *parser) callonRC1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRC1()
}

func (c *current) on_1() (interface{}, error) {
	return ast.NewNoop(c.text)
}

func (p *parser) callon_1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.on_1()
}

func (c *current) onEOF1() (interface{}, error) {
	return ast.Noop{}, nil
}

func (p *parser) callonEOF1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEOF1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := make(storeDict, len(p.cur.state))
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return fmt.Sprintf("%s %s %s", strings.Join(list[:len(list)-1], sep), lastSep, list[len(list)-1])
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := fmt.Sprintf("%q%s", lit.val, ignoreCase)
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
